version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - DATABASE_URL=mysql://root:140610@host.docker.internal:3306/sgb
  # db:
    # image: mysql:5.7
    # environment:
      # MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: mydatabase


